package com.pooitec1.alibaba2.view;

import com.pooitec1.alibaba2.controller.PurchaseController;

import com.pooitec1.alibaba2.view.resources.TableModelListenerPurchaseLine;
import com.pooitec1.alibaba2.view.resources.TableModelPurchaseLine;
import com.pooitec1.alibaba2.view.resources.ValidadorDeCampos;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 *
 * @author nadia
 */
public class JPanel_Comprapaso1 extends javax.swing.JPanel {

    LocalDate fi = LocalDate.now();
    LocalDateTime localDate = LocalDateTime.now();
    ValidadorDeCampos validadorDeCampos;

    //variables de tabla
    private final TableModelPurchaseLine tableModelPurchaseLine;

    PurchaseController controlador;
    private JPanelAplication panelMenu;

    /**
     * Creates new form JPanel_Comprapaso1
     */
    public JPanel_Comprapaso1(JPanelAplication panelMenu, PurchaseController controladorP) {
        this.validadorDeCampos = new ValidadorDeCampos();
        //JTable vacio
        this.tableModelPurchaseLine = new TableModelPurchaseLine();

        this.controlador = controladorP;
        this.panelMenu = panelMenu;
        initComponents();
        this.jLabel_date.setText(fi.toString());
        this.jLabel_time.setText(this.localDate.getHour() + ":" + this.localDate.getMinute() + ":" + this.localDate.getSecond());
        this.jLabel_employee.setText(this.controlador.getNewPurchase().getEmployee().getFirstName());
        this.jtb_purchaseLine.getSelectionModel().addListSelectionListener(new TableModelListenerPurchaseLine(this));

        validadarCampos();

        setupBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_purchaseLine = new javax.swing.JTable();
        jButton_remove = new javax.swing.JButton();
        jButton_product = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel_date = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_time = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel_employee = new javax.swing.JLabel();
        jButton_atras1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("PURCHASE DETAIL:");

        jtb_purchaseLine.setModel(tableModelPurchaseLine);
        jScrollPane1.setViewportView(jtb_purchaseLine);

        jButton_remove.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_remove.setText("REMOVE");
        jButton_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_removeActionPerformed(evt);
            }
        });

        jButton_product.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_product.setText("ADD PRODUCT");
        jButton_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_productActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("DATE:");

        jLabel_date.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("TIME:");

        jLabel_time.setText("jLabel5");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("EMPLOYEE:");

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("NEXT");

        jLabel_employee.setText("jLabel7");

        jButton_atras1.setFont(jButton_atras1.getFont().deriveFont(jButton_atras1.getFont().getStyle() | java.awt.Font.BOLD, jButton_atras1.getFont().getSize()+2));
        jButton_atras1.setText("CANCEL");
        jButton_atras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_atras1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel_time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel_date, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(520, 520, 520)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jButton_remove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_product, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(463, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(288, 288, 288)
                    .addComponent(jButton_atras1)
                    .addContainerGap(746, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel_date))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel_time))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel_employee))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_product, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(512, Short.MAX_VALUE)
                    .addComponent(jButton_atras1)
                    .addGap(65, 65, 65)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_removeActionPerformed
        // this.panelMenu.bloquearBotones(true);
        // this.panelMenu.limpiarPanelContenido();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_removeActionPerformed

    private void jButton_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_productActionPerformed

        JPanel_Comprapaso2 panelPaso2 = new JPanel_Comprapaso2(this.panelMenu, this.controlador);

        panelPaso2.setSize(814, 600);
        this.panelMenu.limpiarPanelContenido();

        this.panelMenu.getjPanel_contenido().add(panelPaso2);
        this.panelMenu.repaint();
        this.panelMenu.validate();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_productActionPerformed

    private void jButton_atras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_atras1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_atras1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_atras1;
    private javax.swing.JButton jButton_product;
    private javax.swing.JButton jButton_remove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_date;
    private javax.swing.JLabel jLabel_employee;
    private javax.swing.JLabel jLabel_time;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtb_purchaseLine;
    // End of variables declaration//GEN-END:variables

    public void seleccionarSeller() {
        //obtiene el indice de la fila seleccionada en la tabla de seller
        int filaSeleccionada = this.jtb_purchaseLine.getSelectedRow();
        // si la fila esta seleccionada, seteamos  buyer auxiliar, llamando al modelo de tabla
        if (filaSeleccionada >= 0) {
            //this.sellerSeleccionado = this.tableModelSeller.getSellerIn(filaSeleccionada);
            //  this.jLabel_sellerName.setText(this.sellerSeleccionado.getName());
            // this.jLabel_sellerAdress.setText(this.sellerSeleccionado.getDirection());
            //this.jLabel_sellerPhone.setText(this.sellerSeleccionado.getPhone());
            // this.jLabel_selleremail.setText(this.sellerSeleccionado.getEmail());

        }
    }

    private void validadarCampos() {
        //this.validadorDeCampos.validarSoloNumero(jtx_productName);
        //this.validadorDeCampos.LimitarCaracteres(jtx_productName, 20);
    }

    private void setupBotones() {
        //  this.validadorDeCampos.habilitarBoton(true, jbtn_cancelar, new Color(176, 128, 118), Color.WHITE, Color.GRAY, Color.BLACK);
    }
}
