package com.pooitec1.alibaba2.view;

import com.pooitec1.alibaba2.controller.LoteProductController;
import com.pooitec1.alibaba2.entity.LoteProduct;
import com.pooitec1.alibaba2.entity.Wharehouse;
import com.pooitec1.alibaba2.view.resources.TableModelListenerWharehouseProduct;
import com.pooitec1.alibaba2.view.resources.TableModelProduct;

/**
 *
 * @author nadia
 */
public class JPanel_WharehouseProduct extends javax.swing.JPanel {

    private final JPanelAplication panelMenu;
    private final LoteProductController controlador;
    private final TableModelProduct tableModelWharehouseProduct;
    private LoteProduct loteProductSelected;

    public JPanel_WharehouseProduct(JPanelAplication panelMenu, LoteProductController controladorL) {

        this.tableModelWharehouseProduct = new TableModelProduct();
        this.panelMenu = panelMenu;
        this.controlador = controladorL;
        initComponents();
        this.jTable_productWharehouse.getSelectionModel().addListSelectionListener(new TableModelListenerWharehouseProduct(this));
        cargarMayoristas();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox_Wharehouse = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_productWharehouse = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel_type = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_sector = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_nivel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_stock = new javax.swing.JLabel();
        jButton_cancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel_expiration = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_seller = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Wharehouse:");

        jComboBox_Wharehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_WharehouseActionPerformed(evt);
            }
        });

        jTable_productWharehouse.setModel(tableModelWharehouseProduct);
        jScrollPane1.setViewportView(jTable_productWharehouse);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Product:");

        jLabel_type.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_type.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Sector:");

        jLabel_sector.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_sector.setText("jLabel5");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Nivel:");

        jLabel_nivel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_nivel.setText("jLabel7");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Stock:");

        jLabel_stock.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_stock.setText("jLabel5");

        jButton_cancel.setText("CANCEL");
        jButton_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Expiration:");

        jLabel_expiration.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_expiration.setForeground(new java.awt.Color(0, 0, 51));
        jLabel_expiration.setText("jLabel7");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("Seller:");

        jLabel_seller.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_seller.setForeground(new java.awt.Color(0, 0, 51));
        jLabel_seller.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_type, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel_sector, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel_nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel_expiration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(114, 114, 114)
                                                .addComponent(jButton_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel_seller, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_Wharehouse, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Wharehouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel_type))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel_nivel)
                    .addComponent(jLabel_sector))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_stock)
                        .addComponent(jLabel5)
                        .addComponent(jLabel_expiration)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel_seller))
                .addGap(46, 46, 46)
                .addComponent(jButton_cancel)
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelActionPerformed
        this.panelMenu.bloquearBotones(true);
        this.panelMenu.limpiarPanelContenido();
    }//GEN-LAST:event_jButton_cancelActionPerformed

    private void jComboBox_WharehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_WharehouseActionPerformed
        String name = (String) jComboBox_Wharehouse.getSelectedItem();
        Wharehouse wharehouseSeleccionado = this.controlador.getWharehouse(name);
        this.tableModelWharehouseProduct.setProducts(this.controlador.getProductByWharehouse(wharehouseSeleccionado));
        this.tableModelWharehouseProduct.fireTableDataChanged();
    }//GEN-LAST:event_jComboBox_WharehouseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JComboBox<String> jComboBox_Wharehouse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_expiration;
    private javax.swing.JLabel jLabel_nivel;
    private javax.swing.JLabel jLabel_sector;
    private javax.swing.JLabel jLabel_seller;
    private javax.swing.JLabel jLabel_stock;
    private javax.swing.JLabel jLabel_type;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_productWharehouse;
    // End of variables declaration//GEN-END:variables

    private void cargarMayoristas() {

        for (Wharehouse wharehouse : this.controlador.getWharehouses()) {
            jComboBox_Wharehouse.addItem(wharehouse.getEmail());
        }
    }

    public void seleccionarProducto() {

        int filaSeleccionada = this.jTable_productWharehouse.getSelectedRow();

        if (filaSeleccionada >= 0) {

            this.loteProductSelected = this.tableModelWharehouseProduct.getProductIn(filaSeleccionada);

            this.jLabel_type.setText(this.loteProductSelected.getProduct().getDescription());
            this.jLabel_stock.setText(this.loteProductSelected.getCantidadActual().toString());
            this.jLabel_sector.setText(this.loteProductSelected.getSector().getDescription());
            this.jLabel_nivel.setText(this.loteProductSelected.getSector().getSectorCode());
            this.jLabel_expiration.setText(this.loteProductSelected.getExpiration().toString());
            this.jLabel_seller.setText(this.loteProductSelected.getProduct().getSeller().getName());

        }
    }

}
